image: python:3

stages: 
  - start_venv
  - install
  - tests
  - build

before_script:
  - pip install --upgrade pip
  - pip install -r requirements.txt
  
start_venv:
  stage: start_venv
  script:
    - source .venv/bin/activate

install:
  stage: install
  script:
    - python -m pip install -r requirements.txt

tests:
  stage: tests
  script:
    - python -m pytest tests/test_api.py

build:
  stage: build
  script:
    - python app.py