image: python:3.13

services:
  - docker:20.10.16-dind

variables:
  DOCKER_HOST: tcp://docker:2375/
  DOCKER_TLS_CERTDIR: ""

before_script:
  - pip install --upgrade pip
  - pip install -r requirements.txt

stages: 
  - install
  - tests
  - build

install:
  stage: install
  script:
    - pip install --upgrade pip
    - pip install -r requirements.txt

tests:
  stage: tests
  script:
    - python -m pytest tests/test_api.py

build:
  stage: build
  script:
    - apk add --no-cache docker
    - docker build -t api-python-flask .
