image: python:3.13

services:
  - docker:20.10.16-dind

variables:
  DOCKER_HOST: tcp://docker:2375/
  DOCKER_TLS_CERTDIR: ""

stages: 
  - install
  - tests
  - build
  - deploy

install:
  stage: install
  script:
    - pip install --upgrade pip
    - pip install -r requirements.txt

tests:
  stage: tests
  script:
    - pip install --upgrade pip
    - pip install -r requirements.txt
    - python -m pytest tests/test_api.py

build:
  stage: build
  script:
    - apt-get update && apt-get install -y docker.io
    - docker build -t api-python-flask .

deploy:
  stage: deploy
  image: node:20
  script:
    - npm i -g vercel
    - vercel --token $VERCEL_TOKEN --prod --confirm
  only:
    - master
  when: on_success
